### ISSUE TITLE
Task: Correct RCO / Neighborhood Info in Property Information Table

### ISSUE THREAD

**Issue by jgrimes86** [CodeForPhilly/vacant-lots-proj#513] opened 2024-04-14 15:42 UTC
## Describe the task
The table of property information has a row for "RCO", but that row displays the neighborhood name, not the RCO name.  The table should be revised to show the correct RCO information in the 'RCO' row and add a 'Neighborhood' row to show the neighborhood name.

For example, the property info for 3810 Old York Road indicates that the RCO is Hunting Park:
![image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/140654473/f9e7cdf1-c2ce-49f1-a82f-814ef43bcf00)

However, 3810 Old York Road is in the neighborhood of Hunting Park:
![image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/140654473/7925c7fa-2b2d-4b82-b617-389747d7a04f)

And the RCO is the Nicetown-Tioga Improvement Team:
![image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/140654473/e6eda5f9-c94e-4972-bc0d-fa12063fff48)

(Side Note:  There is an RCO called Hunting Park Connected, but 3810 Old York Road is not inside that RCO's boundaries)

## Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

**Comment by brandonfcohen1** [comment] 2024-04-14 15:52
duplicate of #511

**Closed by brandonfcohen1** 2024-04-14 15:52 UTC
